version: "3.9"

services:
  server:
    build: ./server
    container_name: node_server
    ports:
      - "5000:5000"
    depends_on:
      - services
    environment:
      - PYTHON_SERVICE_URL=http://services:5001
    networks:
      - app-network

  services:
    build: ./services
    container_name: python_services
    ports:
      - "5001:5001"
    networks:
      - app-network

  web:
    build: ./web
    container_name: react_frontend
    ports:
      - "3000:80"  # serve via Nginx
    depends_on:
      - server
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
